### ISSUE TITLE
some observations

### ISSUE THREAD

**Issue by jdevoo** [ianovir/HIMUServer#2]
Hello Sebastiano, I was looking at this class and noticed a few things using it

- executeRAW and executeUDP are identical - perhaps executeRAW should return `elf.__notifyListeners(data.decode("utf-8"))`
- lFloat is not used in extractSensorData() - I had it at some point as follows `packVal.append(HIMUServer.strings2Floats(p))` (breaking the fact this method says it returns strings :-)
- I noticed, while adding trailer data that the NMEA tuple header is missing a comma between a and b `NMEA.aNMEA.b,NMEA.c`
- TCP data needs to hold off until chunk arrives with valid packSeparator

I know it's a simple helper class but the third item might be useful for the app side. I am experimenting with a pandas version of a HIMUServer...

**Comment by ianovir** [comment]
Hi @jdevoo , thank you for the observations. 
I added the RAW option for all protocols (why to use it only with UDP?) and cleaned up some code as you suggested.

- The NMEA thing seems a serious issue, I'll investigate about it. In the meanwhile, could you provide some sentence(s) presenting this problem? Thank you.
- About the TCP prot. , did you encounter some drawbacks just buffering the input data?

A pandas HIMUserver sounds awesome!! Please let me know how it goes :D
